# SPDX-License-Identifier: MIT
---
# vars file for resource_agents_distro

# AlmaLinux/Rocky: repo is 'ha' on EL8, 'highavailability' on EL9+
_ra_distro_alma_ha_repo: >-
  {%- if ansible_facts['distribution_major_version'] | int <= 8 -%}
    ha
  {%- else -%}
    highavailability
  {%- endif -%}
