# SPDX-License-Identifier: MIT
---
# tasks file for reactor_install
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Install DRBD
  ansible.builtin.include_role:
    name: linbit.drbd.drbd_install
  when: reactor_install_drbd | bool

- name: Check for DRBD Reactor updates
  ansible.builtin.package:
    name: drbd-reactor
    state: "{{ reactor_install_package_state }}"
  register: _reactor_install_packages
  notify: restart_drbd_reactor

- name: Install OCF resource agents from GitHub
  ansible.builtin.include_role:
    name: linbit.drbd_reactor.resource_agents_fetch
  when: reactor_install_resource_agents_github | bool

- name: Configure DRBD Reactor
  ansible.builtin.include_tasks: configure-reactor.yml
  when: _reactor_install_packages is changed  # noqa: no-handler
