# SPDX-License-Identifier: MIT
namespace: linbit
name: drbd_reactor
version: 0.9.0
readme: README.md
authors:
- LINBIT <info@linbit.com>
description: DRBD Reactor installation and HA gateway resource configuration
license:
- MIT
tags:
- linbit
- drbd
- drbdreactor
- ha
- nfs
- iscsi
- gateway
dependencies: {}
repository: https://gitlab.at.linbit.com/ansible-collections/linbit.drbd_reactor
documentation: https://linbit.com/linbit-software-download/
homepage: https://linbit.com
issues: https://gitlab.at.linbit.com/ansible-collections/linbit.drbd_reactor/-/issues
