# SPDX-License-Identifier: MIT
namespace: linbit
name: drbd_reactor
version: 0.9.8
readme: README.md
authors:
  - Ryan Ronnander <rronnander@linbit.com>
  - Matt Kereczman <matt@linbit.com>
  - Michael Troutman <michael@linbit.com>
  - Devin Vance <devin@linbit.com>
description: Install and configure DRBD Reactor
license:
  - MIT
tags:
  - infrastructure
  - linbit
  - drbd
  - drbdreactor
  - ha
dependencies:
  linbit.common: '*'
  linbit.drbd: '*'
repository: https://github.com/LINBIT/ansible-drbd_reactor-collection
documentation: https://github.com/LINBIT/ansible-drbd_reactor-collection
homepage: https://linbit.com
issues: https://github.com/LINBIT/ansible-drbd_reactor-collection/issues
