# SPDX-License-Identifier: MIT-0
---
# defaults file for reactor_install
reactor_install_drbd_path: >-
  {%- if ansible_os_family | lower == 'debian' -%}
    /usr/sbin/drbdadm
  {%- else -%}
    /sbin/drbdadm
  {%- endif -%}
